name: Generate 3W2H on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate 3W2H Text
      run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        ISSUE_BODY="${{ github.event.issue.body }}"
        ISSUE_URL="${{ github.event.issue.html_url }}"
        ISSUE_NUMBER="${{ github.event.issue.number }}"

        # Cria o arquivo de texto com base nas informações do issue
        cat <<EOF > 3W2H_issue_${ISSUE_NUMBER}.txt
        3W2H para o Issue #${ISSUE_NUMBER}

        What: ${ISSUE_TITLE}

        Why: (Adicione a razão aqui)

        Where: (Adicione o local aqui)

        When: (Adicione o tempo aqui)

        How: (Adicione o método aqui)

        How Much: (Adicione o custo aqui)

        Veja o Issue no GitHub: ${ISSUE_URL}
        EOF

    - name: Upload 3W2H Text as artifact
      uses: actions/upload-artifact@v2
      with:
        name: 3W2H_issue_${{ github.event.issue.number }}
        path: 3W2H_issue_${{ github.event.issue.number }}.txt
